recipe: default.v1
language: en
pipeline:
- name: custom.custom_cmd_gen.CustomLLMCommandGenerator
  llm:
    provider: openai
    model: gpt-4-0613
    timeout: 7
    max_tokens: 256
    temperature: 0
    cache:
      no-cache: true
  prompt_template: prompt_templates/time_aware_prompt.jinja2

policies:
- name: FlowPolicy
assistant_id: 20240513-110741-taxonomic-iron
