recipe: default.v1
language: en
pipeline:
- name: custom.custom_cmd_gen.CustomLLMCommandGenerator
  llm:
    provider: self-hosted
    model: dakshvar22/cmd_gen_travel_assistant_l3.1_8b_unsloth_params
    api_base: "http://34.87.9.72:8000/v1"
    timeout: 7
    max_tokens: 256
    temperature: 0
    cache:
      no-cache: true
  prompt_template: prompt_templates/time_aware_prompt.jinja2

policies:
- name: FlowPolicy
assistant_id: 20240513-110741-taxonomic-iron
